// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsg5jl2oQhD8byN7YM0RQQUhfB1xGWWTY',
    appId: '1:1012022062024:web:e3549e885d66594be46efd',
    messagingSenderId: '1012022062024',
    projectId: 'ustaadg-d0a71',
    authDomain: 'ustaadg-d0a71.firebaseapp.com',
    databaseURL: 'https://ustaadg-d0a71-default-rtdb.firebaseio.com',
    storageBucket: 'ustaadg-d0a71.firebasestorage.app',
    measurementId: 'G-G80EXY7BNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ua3W6aP-2EB97Cdo0XIM6vbFQip18Ko',
    appId: '1:1012022062024:android:14e7280f97f84916e46efd',
    messagingSenderId: '1012022062024',
    projectId: 'ustaadg-d0a71',
    databaseURL: 'https://ustaadg-d0a71-default-rtdb.firebaseio.com',
    storageBucket: 'ustaadg-d0a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_eM_YaJAsPrCNtdN292IkK7V3hNhwI0',
    appId: '1:1012022062024:ios:7db5b80837a1df48e46efd',
    messagingSenderId: '1012022062024',
    projectId: 'ustaadg-d0a71',
    databaseURL: 'https://ustaadg-d0a71-default-rtdb.firebaseio.com',
    storageBucket: 'ustaadg-d0a71.firebasestorage.app',
    iosBundleId: 'com.example.ustaadg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_eM_YaJAsPrCNtdN292IkK7V3hNhwI0',
    appId: '1:1012022062024:ios:7db5b80837a1df48e46efd',
    messagingSenderId: '1012022062024',
    projectId: 'ustaadg-d0a71',
    databaseURL: 'https://ustaadg-d0a71-default-rtdb.firebaseio.com',
    storageBucket: 'ustaadg-d0a71.firebasestorage.app',
    iosBundleId: 'com.example.ustaadg',
  );
}
